## Q6.1.1
-----

`np.ndarray()` is the class and `np.array()` is an instance of that class.

## Q6.1.2
-----

```python
np.array((1, 0, 0), (0, 1, 0), (0, 0, 1), dtype=float)
```
There needs to be an extra parentheses between the elements, like below:
```python
np.array(((1, 0, 0), (0, 1, 0), (0, 0, 1)), dtype=float)
```

## Q6.1.3
-----

```python
a = np.array([0, 0, 0])
a = np.array([[0, 0, 0]])
```
The second statement creates a two dimensional array, so adding extra rows is possible.

## Q6.1.4
-----

```python
a, b = np.zeroes((3,)), np.ones((3,))
a.dtype = 'int'
a
b.dtype = 'int'
b
```
Using `.dtype` does not actually change the byte-level repersentation of the array, instead use `.astype('int')`.

In [6]:
import numpy as np
a = np.linspace(1, 48, 48).reshape(3, 4, 4)
print(a)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]

 [[17. 18. 19. 20.]
  [21. 22. 23. 24.]
  [25. 26. 27. 28.]
  [29. 30. 31. 32.]]

 [[33. 34. 35. 36.]
  [37. 38. 39. 40.]
  [41. 42. 43. 44.]
  [45. 46. 47. 48.]]]


In [81]:
# a)
print(a[1, 0, 3])
print('-----------')

# b)
print(a[0, 2])
print('-----------')

# c)
print(a[2])
print('-----------')

# d)
print(a[:, 1, :2])
print('-----------')

# e)
print(a[2,:, :1:-1])
print('-----------')

# f)
print(a[:, ::-1, 0])
print('-----------')

# g)
ia = np.array([[0, 0], [2, 2]])
ja = np.array([[0, 0], [3, 3]])
ka = np.array([[0, 3], [0, 3]])
print(a[ia, ja, ka])
print('-----------')

20.0
-----------
[ 9. 10. 11. 12.]
-----------
[[33. 34. 35. 36.]
 [37. 38. 39. 40.]
 [41. 42. 43. 44.]
 [45. 46. 47. 48.]]
-----------
[[ 5.  6.]
 [21. 22.]
 [37. 38.]]
-----------
[[36. 35.]
 [40. 39.]
 [44. 43.]
 [48. 47.]]
-----------
[[13.  9.  5.  1.]
 [29. 25. 21. 17.]
 [45. 41. 37. 33.]]
-----------
[[ 1.  4.]
 [45. 48.]]
-----------


## Q6.1.6
-----

In [85]:
a = np.array([0, -1, 4.5, 0.5, -0.2, 1.1])
print(a[abs(a) <= 1])

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Q6.1.7
-----

Because the relative tolerance is less than the absolute tolerance, set `rtol` to 0 to make it work.

## Q6.1.8
-----

## Q6.1.9
-----

## Q6.1.10
-----

## Q6.1.11